import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {motion, MotionConfig, useReducedMotion} from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight, ArrowDown, ArrowRight, Check, X, Sun, Moon, Menu, Download, Github, Linkedin, Mail, Copy, Command, Search, Plus, Trash2, ChevronUp, ChevronDown, LogOut, Save, Send, Eye, Settings2, BriefcaseBusiness, UserRound, Layers3, GraduationCap, Award, Inbox, ShieldCheck, Palette, History, ExternalLink, Upload, LockKeyhole, Code2, Database, Network, FileText, RotateCcw, LoaderCircle, MapPin} from 'lucide-react';
import './style.css';

type Content = any;
const API_HEADERS = {'Content-Type':'application/json','X-CSRF-Protection':'1'};
async function api(path:string,opts:RequestInit={}){
  const r=await fetch(path,{...opts,headers:{...API_HEADERS,...opts.headers}});
  const data=await r.json();
  if(!r.ok)throw new Error(data.error||'Something went wrong. Please try again.');
  return data;
}
function useToast(){
  const [message,setMessage]=useState('');
  const timer=useRef<any>(null);
  return [message,(s:string)=>{setMessage(s);clearTimeout(timer.current);timer.current=setTimeout(()=>setMessage(''),4500)}] as const;
}
function Toast({message}:{message:string}){return message?<div className="toast" role="status"><Check size={16}/>{message}</div>:null}
function Modal({open,onOpenChange,title,description,children,className=''}:any){
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={'modal '+className}>
    <Dialog.Title className="sr-only">{title}</Dialog.Title><Dialog.Description className="sr-only">{description||title}</Dialog.Description>
    <Dialog.Close className="icon-button modal-close" aria-label="Close"><X size={20}/></Dialog.Close>{children}
  </Dialog.Content></Dialog.Portal></Dialog.Root>
}
function Reveal({children,className='',delay=0}:any){
  const reduced=useReducedMotion();
  return <motion.div className={className} initial={reduced?false:{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}} transition={{duration:.65,delay,ease:[.2,.7,.2,1]}}>{children}</motion.div>
}
function Label({children,number}:any){return <div className="section-label">{number&&<span>{number} /</span>} {children}</div>}
function ArrowLink({children,href,...rest}:any){return <a className="text-link" href={href} {...rest}>{children}<ArrowUpRight size={17}/></a>}

function DataSculpture(){
 return <div className="sculpture" aria-label="Animated illustration of a data pipeline: ingest, transform, and understand">
  <div className="sculpture-head"><span className="tiny-dot"/> SYSTEMS, WITH INTENTION <span>FIG. 01</span></div>
  <svg viewBox="0 0 500 390" role="img" aria-label="Data flowing through a layered system">
   <defs><pattern id="dots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".15"/></pattern>
   <linearGradient id="layer" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#e3e6c5"/><stop offset="1" stopColor="#b5bd8e"/></linearGradient></defs>
   <rect width="500" height="390" fill="url(#dots)"/>
   <g stroke="currentColor" fill="none" opacity=".15"><ellipse cx="250" cy="214" rx="216" ry="122"/><ellipse cx="250" cy="214" rx="183" ry="104"/><path d="M250 38v310M28 214h444" strokeDasharray="3 7"/></g>
   <g className="packet-line" stroke="var(--accent)" strokeWidth="1.5" fill="none"><path d="M34 253h58l53-31M358 223l52-31h58" strokeDasharray="5 6"/></g>
   <g className="float-stack">
    <path d="M125 237l125-69 125 69v19l-125 70-125-70z" fill="#838e67" stroke="#687152"/>
    <path d="M125 237l125-70 125 70-125 70z" fill="url(#layer)" stroke="#687152"/>
    <path d="M125 195l125-70 125 70v19l-125 70-125-70z" fill="#a4ae84" stroke="#687152"/>
    <path d="M125 195l125-70 125 70-125 70z" fill="#dce0c2" stroke="#687152"/>
    <path d="M125 153l125-70 125 70v19l-125 70-125-70z" fill="#c0c8a3" stroke="#687152"/>
    <path d="M125 153l125-70 125 70-125 70z" fill="#eef0da" stroke="#687152"/>
    <g stroke="#9aa47e" fill="none"><path d="M156 153l94-52 94 52-94 52z"/><path d="M188 136l124 70M219 119l125 70M188 188l124-70M156 171l125-70" opacity=".65"/></g>
    <ellipse cx="250" cy="153" rx="27" ry="15" fill="var(--accent)"/><path d="M241 153l6 4 13-8" fill="none" stroke="#fff6eb" strokeWidth="2"/>
   </g>
   <g fill="var(--muted)" fontSize="10" fontFamily="DM Mono,monospace"><text x="25" y="275">RAW INPUT</text><text x="376" y="178">USEFUL OUTPUT</text><text x="245" y="365">01 → 02 → 03</text></g>
   <g fill="var(--accent)"><circle className="signal" cx="69" cy="253" r="4"/><circle className="signal delay" cx="441" cy="192" r="4"/></g>
  </svg>
  <div className="sculpture-foot"><span>INGEST</span><span>TRANSFORM</span><span>UNDERSTAND <ArrowUpRight size={12}/></span></div>
 </div>
}
function ProjectVisual({type,compact=false}:any){
 if(type==='pipeline')return <div className={'project-visual pipeline-visual '+(compact?'compact':'')} aria-hidden="true">
  <div className="visual-top"><span>AZURE / DATA ARCHITECTURE</span><Database size={17}/></div>
  <div className="pipeline-flow"><div className="pipeline-source"><div className="source-bars"><i/><i/><i/><i/></div><small>SPOTIFY DATA</small></div><span className="flow-connector"/>
  <div className="data-stage bronze"><Layers3/><span>BRONZE</span><small>Raw</small></div><span className="flow-connector"/>
  <div className="data-stage silver"><Layers3/><span>SILVER</span><small>Refined</small></div><span className="flow-connector"/>
  <div className="data-stage gold"><Layers3/><span>GOLD</span><small>Ready</small></div></div>
  <div className="visual-bottom"><span>METADATA-DRIVEN INGESTION</span><span>∆ INCREMENTAL LOAD</span></div>
 </div>;
 if(type==='search')return <div className="project-visual memora-visual" aria-hidden="true"><div className="visual-top"><span>MEMORA / SEMANTIC LEARNING</span><Search size={17}/></div><div className="memora-art"><div className="paper paper-back"/><div className="paper paper-front"><span className="paper-label">A LITTLE MORE CONTEXT.</span><p>Knowledge,<br/><em>connected.</em></p><div className="paper-lines"><i/><i/><i/></div></div><div className="search-chip"><Search size={15}/> Find the meaning, not just the words.<span>↵</span></div></div></div>;
 return <div className="project-visual agents-visual" aria-hidden="true"><div className="visual-top"><span>AGENTIC / INTELLIGENT ROUTING</span><Network size={17}/></div><div className="agent-art"><div className="question-chip">“What does the data tell us?”</div><span className="vertical-line"/><div className="router"><span className="tiny-dot"/> LLM ROUTER</div><div className="branches"/><div className="agent-pair"><div><Database size={20}/><span>SQL</span><small>Query & reason</small></div><div><Code2 size={20}/><span>ETL</span><small>Extract & transform</small></div></div></div></div>
}
function ProjectDetail({project,onClose}:any){
 return <Modal open={!!project} onOpenChange={(v:boolean)=>!v&&onClose()} title={project?.name} className="project-modal">
 {project&&<><ProjectVisual type={project.visual}/><div className="project-detail"><Label>{project.category} · {project.period}</Label><h2>{project.name}</h2><p className="detail-intro">{project.description}</p><h3>What went into it</h3><ul className="detail-list">{project.bullets.map((b:string,i:number)=><li key={i}><ArrowRight size={16}/><span>{b}</span></li>)}</ul><div className="tags">{project.tags.map((t:string)=><span key={t}>{t}</span>)}</div><div className="detail-links">{project.repo&&<ArrowLink href={project.repo} target="_blank" rel="noreferrer">View source</ArrowLink>}{project.url&&<ArrowLink href={project.url} target="_blank" rel="noreferrer">Visit project</ArrowLink>}{!project.repo&&!project.url&&<small>Want to know more? Get in touch to discuss the project.</small>}</div></div></>}
 </Modal>
}
function CommandMenu({open,setOpen,profile}:any){
 const [q,setQ]=useState('');
 const actions=[...['Work','About','Toolkit','Journey','Contact'].map(s=>({label:'Go to '+s,action:()=>document.getElementById(s.toLowerCase())?.scrollIntoView({behavior:'smooth'})})),{label:'Download résumé',action:()=>window.open(profile.resume,'_blank')},{label:'Open admin studio',action:()=>window.location.assign('/admin')}];
 const filtered=actions.filter(a=>a.label.toLowerCase().includes(q.toLowerCase()));
 return <Modal open={open} onOpenChange={setOpen} title="Quick navigation" className="command-modal"><div className="command-input"><Search size={20}/><input autoFocus aria-label="Search pages and actions" placeholder="Where would you like to go?" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="command-results">{filtered.length?filtered.map(a=><button key={a.label} onClick={()=>{setOpen(false);a.action()}}>{a.label}<ArrowUpRight size={17}/></button>):<p>No matching pages. Try “work” or “contact”.</p>}</div><div className="command-hint">A SHORTCUT TO THE GOOD STUFF <kbd>ESC</kbd></div></Modal>
}
function ContactForm({toast}:any){
 const [status,setStatus]=useState(''),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');setStatus('sending');const form=e.currentTarget;
  const d=Object.fromEntries(new FormData(form));
  try{await api('/api/contact',{method:'POST',body:JSON.stringify(d)});setStatus('sent');form.reset();toast('Message saved to Yashraj’s inbox.');}catch(e:any){setStatus('');setError(e.message)}
 }
 return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Your name<input name="name" required maxLength={100} placeholder="Alex Taylor"/></label><label>Email address<input name="email" type="email" required placeholder="alex@company.com"/></label></div><label>What are you thinking?<textarea name="message" required minLength={10} maxLength={4000} rows={3} placeholder="Tell me a little about your project or opportunity…"/></label><div className="honeypot" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="contact-form-bottom"><span>{status==='sent'?'Thank you — your message is in my inbox.':'Delivered to my portfolio inbox.'}</span><button className="button primary" disabled={status==='sending'}>{status==='sending'?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>} Send message</button></div></form>
}

function Portfolio({content,preview=false}: {content:Content,preview?:boolean}){
 const {profile:p,design:d,projects,skills,experience,education,credentials}=content;
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('yr-theme')||d.defaultTheme}catch{return d.defaultTheme}});
 const [filter,setFilter]=useState('All'),[selected,setSelected]=useState<any>(null),[menu,setMenu]=useState(false),[command,setCommand]=useState(false);
 const [toast,notify]=useToast();
 const categories=['All',...Array.from(new Set<string>(projects.map((p:any)=>p.category)))];
 useEffect(()=>{if(!preview){document.title=p.name+' — '+p.role;document.documentElement.dataset.theme=theme}return()=>{if(!preview)delete document.documentElement.dataset.theme}},[theme,p.name,p.role,preview]);
 useEffect(()=>{if(preview)return;const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setCommand(v=>!v)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[preview]);
 function toggle(){const t=theme==='light'?'dark':'light';setTheme(t);try{localStorage.setItem('yr-theme',t)}catch{}}
 async function copyEmail(){try{await navigator.clipboard.writeText(p.email);notify('Email address copied.')}catch{notify('Email: '+p.email)}}
 const style={'--accent':theme==='dark'?`color-mix(in srgb, ${d.accent}, #ffffff 38%)`:d.accent} as React.CSSProperties;
 return <MotionConfig reducedMotion={d.animations?'user':'always'}><div className={'portfolio '+(d.animations?'':'no-motion')+' '+(d.font==='sans'?'sans-headings':'')} style={style} data-theme={theme}>
  <a href="#work" className="skip-link">Skip to projects</a>
  <header className="site-header"><a className="wordmark" href="#" aria-label={p.name+' home'}>{p.name}<span className="brand-dot">.</span></a>
  <nav aria-label="Main navigation" className={menu?'nav-links open':'nav-links'}>{['Work','About','Toolkit'].map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}</a>)}<a href="#contact" className="nav-contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={16}/></a></nav>
  <div className="header-actions"><button className="icon-button command-button" onClick={()=>setCommand(true)} aria-label="Open quick navigation"><Command size={17}/></button><button className="icon-button" onClick={toggle} aria-label={'Switch to '+(theme==='light'?'dark':'light')+' mode'}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><button className="icon-button mobile-menu" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div>
  </header>
  <main>
   <section className="hero container">
    <div className="hero-copy"><Reveal><Label><span className="status-dot"/>{p.role}</Label><h1>{p.heroLead}<br/><em>{p.heroSecond}</em></h1><p className="hero-intro">{p.intro}</p><div className="hero-cta"><a className="button primary" href="#work">Explore my work <ArrowDown size={17}/></a>{p.resume&&<a className="button quiet" href={p.resume} download><Download size={16}/>{p.resumeLabel}</a>}</div></Reveal></div>
    <Reveal className="hero-art" delay={.15}><DataSculpture/></Reveal>
    <div className="hero-bottom"><span><MapPin size={13}/>{p.location}</span><span className="hero-note">A little structure. A lot of possibility.</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={13}/></a></div>
   </section>
   <section className="work-section container section" id="work">
    <Reveal className="section-heading"><div><Label number="01">Selected work</Label><h2>Built to <em>make sense.</em></h2></div><p>A few projects at the intersection<br/>of data, infrastructure, and intelligence.</p></Reveal>
    <div className="work-filter" role="group" aria-label="Filter projects">{categories.map(c=><button key={c} aria-pressed={filter===c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}<span>{c==='All'?projects.length:projects.filter((p:any)=>p.category===c).length}</span></button>)}</div>
    <div className="project-grid">{projects.filter((p:any)=>filter==='All'||p.category===filter).map((pr:any,i:number)=><Reveal className={'project-wrap '+(filter==='All'&&i===0?'featured':'')} key={pr.id} delay={i*.04}>
     <button className="project-card" onClick={()=>setSelected(pr)} aria-label={'Read about '+pr.name}><ProjectVisual type={pr.visual}/><div className="project-text"><div className="project-meta"><span>{String(projects.indexOf(pr)+1).padStart(2,'0')} / {pr.name}</span><ArrowUpRight className="project-arrow" size={22}/></div><h3>{pr.title}</h3><p>{pr.summary}</p><div className="tags">{pr.tags.map((t:string)=><span key={t}>{t}</span>)}</div><span className="case-link">Inside the project <ArrowUpRight size={14}/></span></div></button>
    </Reveal>)}</div>{projects.length===0&&<p className="empty-state">New work is on its way.</p>}
   </section>
   <section className="about-band" id="about"><div className="container about-grid"><Reveal className="about-portrait">{d.showPortrait&&p.portrait?<div className="portrait-frame"><img src={p.portrait} alt={p.fullName} loading="lazy"/><span className="portrait-caption">THE PERSON BEHIND THE PIPELINES.</span><span className="portrait-number">YR / 01</span></div>:<div className="monogram">yr<span>.</span></div>}<div className="about-location"><span className="status-dot"/>{p.availability}</div></Reveal><Reveal className="about-copy"><Label number="02">A little about me</Label><h2>{p.aboutTitle}</h2>{p.about.split('\n').filter(Boolean).map((s:string,i:number)=><p key={i}>{s}</p>)}<div className="about-facts"><div><span>BASED IN</span><strong>{p.location}</strong></div><div><span>LANGUAGES</span><strong>{p.languages}</strong></div></div><div className="about-links">{p.linkedin&&<ArrowLink href={p.linkedin} target="_blank" rel="noreferrer">LinkedIn</ArrowLink>}{p.github&&<ArrowLink href={p.github} target="_blank" rel="noreferrer">GitHub</ArrowLink>}<ArrowLink href={'mailto:'+p.email}>Say hello</ArrowLink></div></Reveal></div></section>
   <section className="container section" id="toolkit"><Reveal className="section-heading"><div><Label number="03">The toolkit</Label><h2>Right tools.<br/><em>Thoughtful systems.</em></h2></div><p>Not a wall of logos.<br/>A practical set of building blocks.</p></Reveal><div className="skills-grid">{skills.map((s:any,i:number)=><Reveal key={i} className="skill-group" delay={i*.06}><span className="skill-index">{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p><div className="skill-items">{s.items.map((s:string)=><span key={s}>{s}</span>)}</div></Reveal>)}</div></section>
   <section className="container section journey-section" id="journey"><Reveal className="section-heading"><div><Label number="04">Along the way</Label><h2>Learning by <em>doing.</em></h2></div></Reveal><div className="journey-grid"><div><h3 className="subsection-title"><BriefcaseBusiness size={17}/>Experience & leadership</h3>{experience.map((e:any,i:number)=><Reveal className="timeline-item" key={i}><span className="timeline-date">{e.period}</span><h4>{e.title}</h4><span className="organization">{e.organization}</span><p>{e.description}</p></Reveal>)}</div>{d.showEducation&&<div><h3 className="subsection-title"><GraduationCap size={19}/>Education</h3>{education.map((e:any,i:number)=><Reveal className="education-item" key={i}><span className="timeline-date">{e.period}</span><h4>{e.title}</h4><p>{e.organization}</p><span className={'result '+(i===0?'major':'')}>{e.result}</span></Reveal>)}</div>}</div>
   {d.showCredentials&&<div className="credentials"><h3 className="subsection-title"><Award size={18}/>A few milestones</h3>{credentials.map((c:any,i:number)=><Reveal className="credential-row" key={i}><span className="credential-type">{c.type}</span><div><h4>{c.title}</h4><p>{c.organization}</p></div><span className="timeline-date">{c.period}</span><Award size={18}/></Reveal>)}</div>}</section>
   <section className="contact-band" id="contact"><div className="container"><Reveal><Label number="05">Start a conversation</Label><div className="contact-heading"><h2>{p.contactTitle}</h2><ArrowUpRight size={64} strokeWidth={1}/></div><p className="contact-intro">{p.contactText}</p><div className="contact-email"><a href={'mailto:'+p.email}>{p.email}</a><button className="icon-button" aria-label="Copy email address" onClick={copyEmail}><Copy size={18}/></button></div></Reveal>{d.showContactForm&&<ContactForm toast={notify}/>}<div className="contact-bottom"><span>{p.location}</span><div>{p.linkedin&&<a href={p.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={20}/></a>}{p.github&&<a href={p.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={20}/></a>}{p.resume&&<a href={p.resume} download>Résumé <ArrowUpRight size={15}/></a>}</div></div></div></section>
  </main>
  <footer className="container site-footer"><span>© {new Date().getFullYear()} {p.name}</span><span>Made with curiosity. Built with intention.</span><a href="/admin"><LockKeyhole size={12}/>Admin</a></footer>
  <ProjectDetail project={selected} onClose={()=>setSelected(null)}/><CommandMenu open={command} setOpen={setCommand} profile={p}/><Toast message={toast}/>
 </div></MotionConfig>
}

function Field({label,value,onChange,multiline=false,help,type='text',...rest}:any){return <label className="field">{label}{multiline?<textarea value={value??''} onChange={e=>onChange(e.target.value)} rows={4} {...rest}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...rest}/>} {help&&<small>{help}</small>}</label>}
function Toggle({label,description,value,onChange}:any){return <label className="toggle-row"><span><strong>{label}</strong>{description&&<small>{description}</small>}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/></label>}
const tabs=[['Profile',UserRound],['Projects',BriefcaseBusiness],['Toolkit',Layers3],['Journey',GraduationCap],['Appearance',Palette],['Inbox',Inbox],['Settings',Settings2]] as const;

function Admin(){
 const [auth,setAuth]=useState<any>(null),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false);
 const [data,setData]=useState<Content>(null),[version,setVersion]=useState(0),[tab,setTab]=useState('Profile'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const [toast,notify]=useToast(),[preview,setPreview]=useState(false),[messages,setMessages]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[uploading,setUploading]=useState(''),[setupPassword,setSetupPassword]=useState(''),[resetMode,setResetMode]=useState(false);
 useEffect(()=>{api('/api/auth/status').then(setAuth).catch(e=>setAuthError(e.message))},[]);
 useEffect(()=>{if(auth?.authenticated)load()},[auth?.authenticated]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 useEffect(()=>{if(!auth?.authenticated)return;if(tab==='Inbox')api('/api/admin/messages').then(setMessages).catch(e=>setError(e.message));if(tab==='Settings')api('/api/admin/history').then(setHistory).catch(e=>setError(e.message))},[tab,auth]);
 async function load(){try{const r=await api('/api/admin/content');setData(r.content);setVersion(r.updated);setDirty(false);setError('')}catch(e:any){setError(e.message)}}
 function update(section:string,key:string,value:any){setData((d:any)=>({...d,[section]:{...d[section],[key]:value}}));setDirty(true)}
 function collection(section:string,items:any[]){setData((d:any)=>({...d,[section]:items}));setDirty(true)}
 function item(section:string,i:number,key:string,value:any){collection(section,data[section].map((x:any,j:number)=>i===j?{...x,[key]:value}:x))}
 function remove(section:string,i:number){if(window.confirm('Remove this item from your draft?'))collection(section,data[section].filter((_:any,j:number)=>i!==j))}
 function move(section:string,i:number,delta:number){const a=[...data[section]];[a[i],a[i+delta]]=[a[i+delta],a[i]];collection(section,a)}
 async function authenticate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setAuthBusy(true);setAuthError('');const v=Object.fromEntries(new FormData(e.currentTarget));if(!auth.configured&&v.password!==v.confirm){setAuthError('Passwords don’t match.');setAuthBusy(false);return}try{await api(auth.configured?'/api/auth/login':'/api/auth/setup',{method:'POST',body:JSON.stringify(v)});setAuth({...auth,authenticated:true,configured:true})}catch(e:any){setAuthError(e.message)}finally{setAuthBusy(false)}}
 async function save(publish:boolean){setBusy(publish?'publish':'save');setError('');try{const r=await api('/api/admin/content',{method:'PUT',body:JSON.stringify({content:data,version,publish})});setVersion(r.updated);setDirty(false);notify(publish?'Published. Your portfolio is up to date.':'Draft saved. The live website hasn’t changed.');if(tab==='Settings')setHistory(await api('/api/admin/history'))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function upload(kind:string,file:File|undefined){if(!file)return;setUploading(kind);setError('');try{const form=new FormData();form.append('file',file);form.append('kind',kind);const r=await fetch('/api/admin/upload',{method:'POST',headers:{'X-CSRF-Protection':'1'},body:form});const result=await r.json();if(!r.ok)throw new Error(result.error);update('profile',kind,result.path);notify('Uploaded. Publish when you’re ready.')}catch(e:any){setError(e.message)}finally{setUploading('')}}
 async function signout(){if(dirty&&!confirm('You have unsaved changes. Sign out anyway?'))return;try{await api('/api/auth/logout',{method:'POST'});setAuth({...auth,authenticated:false});setData(null);setDirty(false)}catch(e:any){setError(e.message)}}
 function exportContent(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='portfolio-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
 async function restore(id:number){if(!confirm('Load this previous version into your editor? Your live site won’t change until you publish.'))return;try{setData(await api('/api/admin/history/'+id));setDirty(true);notify('Previous version loaded into your draft. Review, then publish.')}catch(e:any){setError(e.message)}}
 async function passwordChange(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;setBusy('password');try{await api('/api/auth/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});f.reset();notify('Password changed. Other sessions were signed out.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function passwordReset(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;setAuthBusy(true);setAuthError('');try{await api('/api/auth/reset',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});f.reset();setResetMode(false);setAuthError('Password reset. Sign in with your new password.')}catch(e:any){setAuthError(e.message)}finally{setAuthBusy(false)}}
 const ItemTools=({section,index}:any)=><div className="item-tools"><button className="icon-button" disabled={index===0} onClick={()=>move(section,index,-1)} aria-label="Move up"><ChevronUp size={17}/></button><button className="icon-button" disabled={index===data[section].length-1} onClick={()=>move(section,index,1)} aria-label="Move down"><ChevronDown size={17}/></button><button className="icon-button danger" onClick={()=>remove(section,index)} aria-label="Delete item"><Trash2 size={16}/></button></div>;
 if(!auth||!auth.authenticated)return <div className="admin-login"><a href="/" className="login-back"><ArrowRight size={16}/>Back to portfolio</a><div className="login-card"><div className="admin-mark">yr<span>.</span></div><Label>THE PORTFOLIO STUDIO</Label><h1>{!auth?'One moment.':!auth.owner?'Owner access only.':resetMode?'Reset password.':auth.configured?'Welcome back.':'Make it yours.'}</h1><p>{!auth?'Getting your workspace ready.':!auth.owner?'This studio is private. Open it with the PromptQL account that created this portfolio.':resetMode?'Enter the reset token from Vercel and choose a new admin password.':'Sign in to shape your content, projects, and design.'}</p>
 {auth?.owner&&resetMode&&<form onSubmit={passwordReset}><label className="field">Reset token<input name="token" type="password" required autoComplete="one-time-code"/></label><label className="field">Email<input name="email" type="email" defaultValue="flyonforyou@gmail.com" required autoComplete="username"/></label><label className="field">New password<input name="password" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></label>{authError&&<p className="form-error" role="alert">{authError}</p>}<button className="button primary full" disabled={authBusy}>{authBusy?<LoaderCircle size={17} className="spin"/>:<LockKeyhole size={16}/>} Reset password</button><button className="text-link login-switch" type="button" onClick={()=>{setResetMode(false);setAuthError('')}}>Back to sign in <ArrowUpRight size={15}/></button></form>}
 {auth?.owner&&!resetMode&&<form onSubmit={authenticate}><label className="field">Email<input name="email" type="email" defaultValue="flyonforyou@gmail.com" required autoComplete="username"/></label><label className="field">Password<input name="password" type="password" required minLength={auth.configured?1:12} maxLength={256} autoComplete={auth.configured?'current-password':'new-password'} onChange={e=>setSetupPassword(e.target.value)}/></label>{!auth.configured&&<><div className="password-strength"><span style={{width:Math.min(100,setupPassword.length/16*100)+'%'}}/></div><small>At least 12 characters. Use a unique password.</small><label className="field">Confirm password<input name="confirm" type="password" required minLength={12} autoComplete="new-password"/></label></>}{authError&&<p className="form-error" role="alert">{authError}</p>}<button className="button primary full" disabled={authBusy}>{authBusy?<LoaderCircle size={17} className="spin"/>:<LockKeyhole size={16}/>} {auth.configured?'Sign in to studio':'Create admin account'}</button>{auth.configured&&<button className="text-link login-switch" type="button" onClick={()=>{setResetMode(true);setAuthError('')}}>Reset password on Vercel <ArrowUpRight size={15}/></button>}</form>}{!auth&&authError&&<p role="alert">{authError}</p>}<div className="login-security"><ShieldCheck size={16}/>Owner-restricted · Secure session · Private studio</div></div><p className="login-foot">Your ideas. Your space. Your portfolio.</p></div>;
 if(!data)return <div className="loading-screen"><LoaderCircle className="spin"/><p>{error||'Opening your studio…'}</p>{error&&<button className="button" onClick={load}>Try again</button>}</div>;
 return <div className="admin-shell"><aside className="admin-sidebar"><a className="studio-brand" href="/">yr<span>.</span><small>PORTFOLIO<br/>STUDIO</small></a><div className="workspace-label">YOUR WORKSPACE</div><nav aria-label="Studio sections">{tabs.map(([name,Icon])=><button key={name} onClick={()=>{setTab(name);setPreview(false);setError('')}} className={tab===name&&!preview?'active':''}><Icon size={18}/>{name}</button>)}</nav><div className="sidebar-bottom"><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={17}/>View portfolio</a><button onClick={signout}><LogOut size={17}/>Sign out</button><div className="owner-badge"><div>{data.profile.name.charAt(0)}</div><span>{data.profile.name}<small>Portfolio owner</small></span><ShieldCheck size={15}/></div></div></aside>
 <div className="admin-main"><header className="studio-header"><div><span className={'save-dot '+(dirty?'unsaved':'')}/>{dirty?'Unsaved changes':'Draft saved'}<span className="studio-header-date">{new Date(version*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span></div><div className="studio-actions"><button className="button small quiet" onClick={()=>setPreview(!preview)}><Eye size={16}/>{preview?'Back to editor':'Preview'}</button><button className="button small outline" disabled={!!busy} onClick={()=>save(false)}><Save size={15}/>{busy==='save'?'Saving…':'Save draft'}</button><button className="button small primary" disabled={!!busy} onClick={()=>save(true)}><ArrowUpRight size={16}/>{busy==='publish'?'Publishing…':'Publish'}</button></div></header>
 {error&&<div className="studio-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {preview?<div className="preview-area"><div className="preview-banner"><Eye size={15}/>Previewing your current draft. Visitors still see the last published version.</div><Portfolio content={data} preview/></div>:<div className="editor-content"><div className="editor-title"><Label>YOUR PORTFOLIO, YOUR WAY</Label><h1>{tab==='Profile'?'A good first impression.':tab==='Projects'?'Let your work speak.':tab==='Toolkit'?'Your building blocks.':tab==='Journey'?'The story so far.':tab==='Appearance'?'Set the right tone.':tab==='Inbox'?'Keep the conversation going.':'A little housekeeping.'}</h1><p>{tab==='Inbox'?'Messages from your portfolio contact form. These are stored here, not forwarded by email.':tab==='Settings'?'Manage security, content backups, and publishing history.':'Edit below, preview your changes, and publish when it feels right.'}</p></div>
 {tab==='Profile'&&<>
  <section className="editor-card"><h2><UserRound size={19}/>The essentials</h2><div className="form-grid"><Field label="Display name" value={data.profile.name} onChange={(v:string)=>update('profile','name',v)}/><Field label="Full name" value={data.profile.fullName} onChange={(v:string)=>update('profile','fullName',v)}/><Field label="Role / specialization" value={data.profile.role} onChange={(v:string)=>update('profile','role',v)}/><Field label="Location" value={data.profile.location} onChange={(v:string)=>update('profile','location',v)}/><Field label="Public email" type="email" value={data.profile.email} onChange={(v:string)=>update('profile','email',v)}/><Field label="Availability note" value={data.profile.availability} onChange={(v:string)=>update('profile','availability',v)}/></div></section>
  <section className="editor-card"><h2><FileText size={19}/>The opening lines</h2><div className="form-grid"><Field label="Headline · first line" value={data.profile.heroLead} onChange={(v:string)=>update('profile','heroLead',v)}/><Field label="Headline · second line" value={data.profile.heroSecond} onChange={(v:string)=>update('profile','heroSecond',v)}/></div><Field label="Introduction" multiline value={data.profile.intro} onChange={(v:string)=>update('profile','intro',v)}/><Field label="About heading" value={data.profile.aboutTitle} onChange={(v:string)=>update('profile','aboutTitle',v)}/><Field label="About you" multiline rows={6} help="Separate paragraphs with a blank line." value={data.profile.about} onChange={(v:string)=>update('profile','about',v)}/><Field label="Languages" value={data.profile.languages} onChange={(v:string)=>update('profile','languages',v)}/></section>
  <section className="editor-card"><h2><Upload size={19}/>Portrait & résumé</h2><div className="upload-grid"><div className="portrait-upload"><img src={data.profile.portrait} alt="Current portrait"/><label className="button outline small"><Upload size={15}/>{uploading==='portrait'?'Uploading…':'Change portrait'}<input type="file" accept="image/png,image/jpeg,image/webp" hidden disabled={!!uploading} onChange={e=>upload('portrait',e.target.files?.[0])}/></label><small>JPG, PNG, WebP · up to 10 MB</small></div><div><p className="upload-note">Your résumé download</p><a className="text-link" href={data.profile.resume} target="_blank" rel="noreferrer">Open current PDF <ExternalLink size={15}/></a><label className="button outline small upload-button"><Upload size={15}/>{uploading==='resume'?'Uploading…':'Replace PDF'}<input type="file" accept="application/pdf" hidden disabled={!!uploading} onChange={e=>upload('resume',e.target.files?.[0])}/></label><small>PDF · up to 10 MB / 20 pages. Check it for personal details before uploading.</small><Field label="Download button text" value={data.profile.resumeLabel} onChange={(v:string)=>update('profile','resumeLabel',v)}/></div></div></section>
  <section className="editor-card"><h2><Mail size={19}/>Links & contact</h2><div className="form-grid">{['linkedin','github'].map(k=><Field key={k} label={k==='linkedin'?'LinkedIn URL':'GitHub URL (optional)'} value={data.profile[k]} onChange={(v:string)=>update('profile',k,v)} type="url"/>)}</div><Field label="Contact heading" value={data.profile.contactTitle} onChange={(v:string)=>update('profile','contactTitle',v)}/><Field label="Contact introduction" multiline value={data.profile.contactText} onChange={(v:string)=>update('profile','contactText',v)}/></section>
 </>}
 {tab==='Projects'&&<>{data.projects.map((p:any,i:number)=><section className="editor-card" key={p.id}><div className="editor-card-heading"><h2><span className="editor-number">{String(i+1).padStart(2,'0')}</span>{p.name||'Untitled project'}</h2><ItemTools section="projects" index={i}/></div><div className="form-grid"><Field label="Project name" value={p.name} onChange={(v:string)=>item('projects',i,'name',v)}/><Field label="Category" value={p.category} onChange={(v:string)=>item('projects',i,'category',v)}/></div><Field label="Editorial headline" value={p.title} onChange={(v:string)=>item('projects',i,'title',v)}/><Field label="Short summary" multiline value={p.summary} onChange={(v:string)=>item('projects',i,'summary',v)}/><Field label="Project description" multiline value={p.description} onChange={(v:string)=>item('projects',i,'description',v)}/><Field label="Highlights · one per line" multiline value={p.bullets.join('\n')} onChange={(v:string)=>item('projects',i,'bullets',v.split('\n'))}/><Field label="Technologies · comma separated" value={p.tags.join(', ')} onChange={(v:string)=>item('projects',i,'tags',v.split(',').map(s=>s.trim()))}/><div className="form-grid"><Field label="Period" value={p.period} onChange={(v:string)=>item('projects',i,'period',v)}/><label className="field">Illustration<select value={p.visual} onChange={e=>item('projects',i,'visual',e.target.value)}><option value="pipeline">Data pipeline</option><option value="search">Semantic search</option><option value="agents">Agent routing</option></select></label><Field label="Live URL (optional)" value={p.url} onChange={(v:string)=>item('projects',i,'url',v)} type="url"/><Field label="Source code URL (optional)" value={p.repo} onChange={(v:string)=>item('projects',i,'repo',v)} type="url"/></div></section>)}<button className="add-item" onClick={()=>collection('projects',[...data.projects,{id:crypto.randomUUID(),name:'New project',category:'Data Engineering',title:'Give this project a headline.',period:'',summary:'',description:'',bullets:[],tags:[],visual:'pipeline',url:'',repo:''}])}><Plus size={18}/>Add a project</button></>}
 {tab==='Toolkit'&&<>{data.skills.map((s:any,i:number)=><section className="editor-card" key={i}><div className="editor-card-heading"><h2>{s.title||'Skill group'}</h2><ItemTools section="skills" index={i}/></div><Field label="Group name" value={s.title} onChange={(v:string)=>item('skills',i,'title',v)}/><Field label="Description" value={s.description} onChange={(v:string)=>item('skills',i,'description',v)}/><Field label="Skills · one per line" multiline value={s.items.join('\n')} onChange={(v:string)=>item('skills',i,'items',v.split('\n'))}/></section>)}<button className="add-item" onClick={()=>collection('skills',[...data.skills,{title:'New skill group',description:'',items:[]}])}><Plus size={18}/>Add a skill group</button></>}
 {tab==='Journey'&&<>{[['experience','Experience & leadership',{title:'New role',organization:'',period:'',description:''}],['education','Education',{title:'New qualification',organization:'',period:'',result:''}],['credentials','Certifications & awards',{title:'New milestone',organization:'',period:'',type:'Certification'}]].map(([key,title,blank]:any)=><section key={key} className="journey-editor"><h2 className="editor-group-title">{title}</h2>{data[key].map((e:any,i:number)=><div className="editor-card" key={i}><div className="editor-card-heading"><h2>{e.title}</h2><ItemTools section={key} index={i}/></div><div className="form-grid">{Object.keys(blank).map(k=><Field key={k} label={k==='title'?'Title':k.charAt(0).toUpperCase()+k.slice(1)} value={e[k]} multiline={k==='description'} onChange={(v:string)=>item(key,i,k,v)}/>)}</div></div>)}<button className="add-item" onClick={()=>collection(key,[...data[key],blank])}><Plus size={18}/>Add {key==='experience'?'experience':key==='education'?'education':'milestone'}</button></section>)}</>}
 {tab==='Appearance'&&<>
  <section className="editor-card"><h2><Palette size={19}/>Color & character</h2><p className="card-description">A restrained palette. A distinctive voice. Make this feel like you.</p><label className="field">Accent color</label><div className="color-presets">{[['Terracotta','#a7462d'],['Forest','#32604b'],['Ink blue','#315b8a'],['Mulberry','#854564'],['Charcoal','#414846']].map(([n,c])=><button key={c} className={data.design.accent===c?'selected':''} onClick={()=>update('design','accent',c)}><span style={{background:c}}>{data.design.accent===c&&<Check size={15}/>}</span>{n}</button>)}</div><div className="custom-color"><input aria-label="Custom accent color" type="color" value={data.design.accent} onChange={e=>update('design','accent',e.target.value)}/><span>{data.design.accent}</span><small>Custom accent · choose a dark shade for readable contrast.</small></div><div className="form-grid"><label className="field">Heading style<select value={data.design.font} onChange={e=>update('design','font',e.target.value)}><option value="editorial">Editorial · expressive serif</option><option value="sans">Modern · clean sans serif</option></select></label><label className="field">Default theme<select value={data.design.defaultTheme} onChange={e=>update('design','defaultTheme',e.target.value)}><option value="light">Light · warm paper</option><option value="dark">Dark · warm charcoal</option></select><small>Visitors can override this with the theme toggle.</small></label></div></section>
  <section className="editor-card"><h2><Settings2 size={19}/>Make room for what matters</h2><Toggle label="Motion & animation" description="Gentle entrances, floating layers, and flowing data. Respects reduced-motion preferences." value={data.design.animations} onChange={(v:boolean)=>update('design','animations',v)}/>{[['showPortrait','Profile portrait'],['showContactForm','Contact form'],['showEducation','Education'],['showCredentials','Certifications & awards']].map(([k,l])=><Toggle key={k} label={l} value={data.design[k]} onChange={(v:boolean)=>update('design',k,v)}/>)}</section>
 </>}
 {tab==='Inbox'&&<section className="inbox-list"><div className="inbox-heading"><span>{messages.length} messages · {messages.filter(m=>!m.read).length} unread</span><button className="button small outline" onClick={()=>api('/api/admin/messages').then(setMessages).catch(e=>setError(e.message))}><RotateCcw size={14}/>Refresh</button></div>{!messages.length?<div className="inbox-empty"><Inbox size={38} strokeWidth={1}/><h2>A quiet inbox, for now.</h2><p>When someone sends a message through your portfolio,<br/>it will land right here.</p></div>:messages.map(m=><div className={'editor-card message-card '+(!m.read?'unread':'')} key={m.id}><div className="message-heading"><div><h2>{m.name}{!m.read&&<span className="unread-label">New</span>}</h2><a href={'mailto:'+m.email}>{m.email}</a></div><span>{new Date(m.created*1000).toLocaleString()}</span></div><p className="message-body">{m.message}</p><div className="message-actions"><a className="button outline small" href={'mailto:'+m.email+'?subject='+encodeURIComponent('Re: Your portfolio message')}><Mail size={15}/>Reply by email</a>{!m.read&&<button className="button small quiet" onClick={async()=>{try{await api('/api/admin/messages/'+m.id,{method:'PATCH'});setMessages(messages.map(x=>x.id===m.id?{...x,read:1}:x))}catch(e:any){setError(e.message)}}}><Check size={15}/>Mark read</button>}<button className="icon-button danger" aria-label="Delete message" onClick={async()=>{if(confirm('Delete this message permanently?'))try{await api('/api/admin/messages/'+m.id,{method:'DELETE'});setMessages(messages.filter(x=>x.id!==m.id))}catch(e:any){setError(e.message)}}}><Trash2 size={16}/></button></div></div>)}</section>}
 {tab==='Settings'&&<>
  <section className="editor-card"><h2><ShieldCheck size={19}/>Account security</h2><p className="card-description">Admin access requires both your owner account and this password. Sessions expire after 8 hours.</p><form onSubmit={passwordChange}><div className="form-grid"><label className="field">Current password<input name="current" type="password" autoComplete="current-password" required/></label><label className="field">New password<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={256}/></label></div><button className="button outline" disabled={!!busy}><LockKeyhole size={16}/>Update password</button></form></section>
  <section className="editor-card"><h2><Download size={19}/>Your content, to keep</h2><p className="card-description">Export your current editor content as JSON. Media files are referenced by path and aren’t included in this content-only backup.</p><div className="backup-actions"><button className="button outline" onClick={exportContent}><Download size={16}/>Export content</button><label className="button outline"><Upload size={16}/>Import content<input type="file" accept="application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());for(const k of ['profile','design','projects','skills','experience','education','credentials'])if(!(k in d))throw new Error('This isn’t a portfolio content export.');if(!d.profile.name||!Array.isArray(d.projects)||!Array.isArray(d.skills)||!Array.isArray(d.experience)||!Array.isArray(d.education)||!Array.isArray(d.credentials))throw new Error('This file has an invalid structure.');const validated=await api('/api/admin/validate',{method:'POST',body:JSON.stringify(d)});if(confirm('Replace your draft with this content?')){setData(validated);setDirty(true);notify('Content imported into editor. Save or publish when ready.')}}catch(e:any){setError(e.message)}}}/></label></div></section>
  <section className="editor-card"><h2><History size={19}/>Publishing history</h2><p className="card-description">The last 10 published versions are kept. Restore loads a version into the editor without changing the live site.</p>{!history.length?<p className="history-empty">Your first publish will create a restore point.</p>:history.map(h=><div className="history-row" key={h.id}><div><strong>Version {h.id}</strong><small>Replaced {new Date(h.created*1000).toLocaleString()}</small></div><button className="button outline small" onClick={()=>restore(h.id)}><RotateCcw size={14}/>Restore to draft</button></div>)}</section>
  <div className="hosting-note"><ShieldCheck size={22}/><div><strong>Your private preview is hosted in PromptQL.</strong><p>This app is accessible to this bot’s participants. A public portfolio address or custom domain requires a separate deployment.</p></div></div>
 </>}
 <div className="editor-footer"><ShieldCheck size={14}/>Your edits stay in draft until you publish.</div>
 </div>}
 </div><Toast message={toast}/></div>
}

function App(){
 const [content,setContent]=useState<any>(null),[error,setError]=useState('');
 const admin=window.location.pathname.startsWith('/admin');
 useEffect(()=>{if(!admin)api('/api/content').then(setContent).catch(e=>setError(e.message))},[admin]);
 if(admin)return <Admin/>;
 if(error)return <div className="loading-screen"><h1>Let’s try that again.</h1><p>{error}</p><button className="button primary" onClick={()=>location.reload()}>Reload portfolio</button></div>;
 if(!content)return <div className="loading-screen"><div className="loading-mark">yr<span>.</span></div><span className="loading-line"/><p>A little structure. A lot of possibility.</p></div>;
 return <Portfolio content={content}/>
}
createRoot(document.getElementById('root')!).render(<App/>);
